image: node:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd matsmart
    - npm install
  artifacts:
    paths:
      - ./node_modules

prettier:
  stage: test
  script:
    - npx prettier --check ./src

typescript:
  stage: test
  script:
    - npx tsc --noEmit
