image: node:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd matsmart
    - npm install
  artifacts:
    paths:
      - node_modules

prettier:
  stage: test
  script:
    - ./node_modules/.bin/prettier --check src/* test/*

typescript:
  stage: test
  script:
    - ./node_modules/.bin/tsc --noEmit --skipLibCheck
