image: node:latest

cache:
  paths:
    - matsmart/node_modules/

lint:
  stage: .pre
  before_script:
    - cd matsmart
    - npm install
  script:
    - npm run lint

build:
  stage: build
  before_script:
    - cd matsmart
    - npm install
  script:
    - npm run build

prettier:
  stage: test
  before_script:
    - cd matsmart
    - npm install prettier
  script:
    - npx prettier --check ./src

typescript:
  stage: test
  before_script:
    - cd matsmart
    - npm install
  script:
    - npx tsc --noEmit

unit_test:
  stage: test
  before_script:
    - cd matsmart
    - npm install
  script:
    - npm test