image: node:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd matsmart
    - npm install

prettier:
  stage: test
  script:
    - cd matsmart
    - npm install prettier
    - npx prettier --check ./src

typescript:
  stage: test
  script:
    - cd matsmart
    - npm install typescript
    - npx tsc --noEmit
