image: node:latest

cache:
  paths:
    - matsmart/node_modules/

lint:
  stage: .pre
  script:
    - cd matsmart
    - npm install
    - npm run lint

build:
  stage: build
  script:
    - cd matsmart
    - npm install
    - npm run build

prettier:
  stage: test
  script:
    - cd matsmart
    - npm install prettier
    - npx prettier --check ./src

typescript:
  stage: test
  script:
    - cd matsmart
    - npm install typescript
    - npx tsc --noEmit
